### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by Uraforclain** [IBM/alexa-skill-watson-conversation#1]
Hey nehidloff! Firstly i would like to thank you for this tutorial! thumbs up for that. I kinda get everything and all the steps you have mentioned thus far other than the part on redis and openwhisk.

1. Watson Side i get it till the import conversation.
2. However i know i need to create openwhisk grab that URL and paste it at amazon side. This is the part that i don't get. Could you explain how i could set up openwhisk / redis. From what i see so far, i need to pay for it. Is there no free version? if using the docker is free then where do i get the IPaddress and port number from?
3. Alexa Side i get it.

**Comment by MuhammadAshraff** [comment]
Same problem as you, what I'm thinking of, why not just not go through Redis and just go straight to Watson Conversation back to IBM Cloud Function and to Alexa ? Anyone have any idea ?

**Comment by stevemart** [comment]
poking @nheidloff

**Comment by MuhammadAshraff** [comment]
Bump

**Comment by markstur** [comment]
Looks like we won't expand this pattern outside if IBM Cloud. Functions and Redis are documented for that path.  Unfortunately Redis is not free.
