### ISSUE TITLE
Extend the "And finally. Wait for user input" response time. 

### ISSUE THREAD

**Issue by CDIDEV** [IBM/alexa-skill-watson-conversation#17]
We've noticed that if a user doesn't respond to an intent, say, within 5 seconds, the skill stops. 

In the Conversation > Dialog tool, we're using "And finally. Wait for user input". Is there a way to extend that time waiting for user input?

**Comment by markstur** [comment]
I see a couple of Amazon forum responses that say you cannot customize this.

https://forums.developer.amazon.com/questions/73766/is-it-possible-to-make-alexa-wait-longer-for-respo.html
