### ISSUE TITLE
Changes to the Bluemix Interface

### ISSUE THREAD

**Issue by brettforbes** [IBM/alexa-skill-watson-conversation#25]
Hi,

Just a small one, but the Bluemix interface has now changed so the webcall url is provided on the Bluemix screen under the HTTP option, and you do not have to reconstruct it from the REST url, using sed.

You could just change your screen shot like the one below, and delete the bit about constructing the url.
![image](https://user-images.githubusercontent.com/24556510/36883490-cd1b1896-1e2e-11e8-91c1-9d56b4588de7.png)

**Comment by markstur** [comment]
Closed by #26
